(CAT-836) - Bump Jquery to 3.7.1 & Bootstrap 4.1.3
puppetlabs/rspec-puppet pull request #72
Opened 2023-09-29 09:21 UTC by jordanbreen28

## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified.

2023-09-29 09:52 UTC, ekohl requested changes
I don't see any changes to `docs/_layouts/base.html` and `docs/_layouts/cards.html` which are the actual files that reference the jquery files.

2023-09-29 09:52 UTC, ekohl commented on docs/assets/plugins/jquery-scrollTo/demo/index.old.html
This filename is `.old.html` and in demo. Can't we simply delete the whole demo directory?

2023-09-29 09:52 UTC, ekohl commented on docs/assets/plugins/lightbox/examples/index.html
This is in examples. Perhaps just delete the examples?

2023-09-29 10:00 UTC, jordanbreen28 commented on docs/assets/plugins/lightbox/examples/index.html
Currently toying around with what we actually need here, will mark this as draft to avoid confusion!

2023-10-02 08:13 UTC, GSPatton approved these changes

2023-10-02 08:13 UTC, merged